/* This file was auto-generated by KreMLin! */

#include "CBS.h"

bool CBS_uu___is_MkCBS(CBS_cbs_t projectee)
{
  return true;
}

uint8_t *CBS___proj__MkCBS__item__data(CBS_cbs_t projectee)
{
  CBS_cbs_t scrut = projectee;
  uint8_t *data = scrut.data;
  return data;
}

uint32_t CBS___proj__MkCBS__item__len(CBS_cbs_t projectee)
{
  CBS_cbs_t scrut = projectee;
  uint32_t len = scrut.len;
  return len;
}

bool CBS_cbs_get_u(CBS_cbs_t *cbs, uint32_t *out, uint32_t num)
{
  CBS_cbs_t cbs0 = cbs[0U];
  CBS_cbs_t scrut0 = cbs0;
  uint32_t len = scrut0.len;
  if (len >= num)
  {
    for (uint32_t i = (uint32_t)0U; i < num; i = i + (uint32_t)1U)
    {
      CBS_cbs_t scrut = cbs0;
      uint8_t *data = scrut.data;
      uint8_t bi = data[i];
      uint32_t uu____198 = out[0U];
      uint32_t uu____197 = uu____198 << (uint32_t)8U;
      uint32_t uu____196 = uu____197 + (uint32_t)bi;
      out[0U] = uu____196;
    }
    return true;
  }
  else
    return false;
}

bool CBS_cbs_get_u8(CBS_cbs_t *cbs, uint8_t *out)
{
  CBS_cbs_t cbs0 = cbs[0U];
  CBS_cbs_t scrut = cbs0;
  uint32_t len = scrut.len;
  if (len > (uint32_t)0U)
  {
    CBS_cbs_t scrut = cbs0;
    uint8_t *data = scrut.data;
    uint8_t uu____248 = data[0U];
    out[0U] = uu____248;
    return true;
  }
  else
    return false;
}

