/* This file was auto-generated by KreMLin! */
#include "kremlib.h"
#ifndef __CBS_H
#define __CBS_H





typedef uint8_t *CBS_uint8_p;

typedef struct 
{
  uint8_t *data;
  uint32_t len;
}
CBS_cbs_t;

bool CBS_cbs_skip(CBS_cbs_t *cbs, uint32_t num);

bool CBS_cbs_get(CBS_cbs_t *cbs, uint8_t **out, uint32_t num);

bool CBS_cbs_get_u(CBS_cbs_t *cbs, uint32_t *out, uint32_t num);

bool CBS_cbs_get_u8(CBS_cbs_t *cbs, uint8_t *out);

bool CBS_cbs_get_u16(CBS_cbs_t *cbs, uint16_t *out);

bool CBS_cbs_get_u24(CBS_cbs_t *cbs, uint32_t *out);

bool CBS_cbs_get_u32(CBS_cbs_t *cbs, uint32_t *out);
#endif
