/* This file was auto-generated by KreMLin! */
#include "kremlib.h"
#ifndef __FStar_H
#define __FStar_H


#include "Prims.h"
#include "Spec_Loops.h"
#include "CBS.h"


typedef void *FStar_Pervasives_ex_pre;

typedef enum {
  FStar_Pervasives_PpxDerivingShow,
  FStar_Pervasives_PpxDerivingShowConstant,
  FStar_Pervasives_CInline,
  FStar_Pervasives_Substitute,
  FStar_Pervasives_Gc,
  FStar_Pervasives_Comment
}
FStar_Pervasives___internal_ocaml_attributes_tags;

typedef struct 
{
  FStar_Pervasives___internal_ocaml_attributes_tags tag;
  union {
    struct  { Prims_string _0; } case_PpxDerivingShowConstant;
    struct  { Prims_string _0; } case_Comment;
  }
  ;
}
FStar_Pervasives___internal_ocaml_attributes;

typedef void *FStar_Set_eqtype;

extern void FStar_PropositionalExtensionality_axiom();

extern Prims_int FStar_Int_logand(Prims_pos x0, Prims_int x1, Prims_int x2);

extern Prims_int FStar_Int_logxor(Prims_pos x0, Prims_int x1, Prims_int x2);

extern Prims_int FStar_Int_logor(Prims_pos x0, Prims_int x1, Prims_int x2);

extern Prims_int FStar_Int_lognot(Prims_pos x0, Prims_int x1);

extern Prims_int FStar_Int_shift_right(Prims_pos x0, Prims_int x1, Prims_nat x2);
#endif
